version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: 3.9-slim # Permite trocar a versão facilmente
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data/assets:/app/data/assets
    environment:
      - APP_ENV=development
      - PYTHONUNBUFFERED=1 # Melhora logs do Python
    restart: unless-stopped # Recuperação automática
    command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
